version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.PACKAGES_TOKEN}}

updates:
- package-ecosystem: npm
  directory: "/b3"
  schedule:
    interval: "weekly"
  registries:
    - npm-github
- package-ecosystem: npm
  directory: "/b4"
  schedule:
    interval: "weekly"
  registries:
    - npm-github
- package-ecosystem: bundler
  directory: "/web.test"
  schedule:
    interval: "weekly"
